#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const outDir = path.join('public', 'assets', 'pixel');
fs.mkdirSync(outDir, { recursive: true });

const assets = {
  'quest-star.svg': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" shape-rendering="crispEdges" role="img" aria-label="Quest star icon">
  <rect width="32" height="32" fill="none"/>
  <path fill="#57331f" d="M14 2h4v6h6v4h4v6h-6v6h-4v6h-4v-6H8v-6H2v-6h6V8h6z"/>
  <path fill="#ffd36d" d="M14 4h4v7h7v4h-7v7h-4v-7H7v-4h7z"/>
  <path fill="#fff2a6" d="M15 6h2v7h7v2h-7v7h-2v-7H8v-2h7z"/>
</svg>
`,
  'market-ribbon.svg': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 32" shape-rendering="crispEdges" role="img" aria-label="Moonberry market ribbon">
  <rect x="0" y="8" width="96" height="18" fill="#5c3723"/>
  <rect x="4" y="5" width="88" height="18" fill="#d78345"/>
  <rect x="8" y="8" width="80" height="12" fill="#ffd36d"/>
  <path fill="#8f4f30" d="M0 8h14v18H0l7-9zM82 8h14l-7 9 7 9H82z"/>
  <text x="48" y="18" text-anchor="middle" font-family="monospace" font-size="8" font-weight="700" fill="#4d2b1c">MOONBERRY</text>
</svg>
`,
};

for (const [file, content] of Object.entries(assets)) {
  fs.writeFileSync(path.join(outDir, file), content);
  console.log(`wrote ${path.join(outDir, file)}`);
}

const provenance = `# Pixel asset provenance\n\nThese SVG support assets are handcrafted deterministic project assets generated by \`scripts/generate-assets.mjs\`. Runtime character, terrain, crop, weather, and UI textures are drawn from code in \`src/game/assets/createPixelArtTextures.ts\` using Phaser canvas textures.\n\n- PixelLab MCP was not used.\n- Assets are original, local/offline, and intentionally avoid direct Stardew Valley lookalikes.\n- License follows the repository license.\n`;
fs.writeFileSync(path.join(outDir, 'README.md'), provenance);
console.log(`wrote ${path.join(outDir, 'README.md')}`);
